config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get '/signup' => 'users#new'
  resources :users, except: [:new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/users' => 'users#create'

  resources :line_items
  resources :carts
  resources :reviews
  resources :products
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the shop #{@user.name}"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all reviews created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="form-container">
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="card card-container">
    <p class='title'>Sign Up</p>
    <form class="form-signin">
      <%= f.label :name %>
      <%= f.text_field :name, id: "inputName", class: "form-control", autofocus: true %>
      <%= f.label :email %>
      <%= f.email_field :email, id: "inputEmail", class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, id: "inputPassword", class: "form-control" %>
      <%= f.label :confirm_password %>
      <%= f.password_field :password_confirmation, id: "inputPassword", class: "form-control" %>
      <!-- <div id="remember" class="checkbox">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div> -->
      <%= f.submit(@user.new_record? ? 'Sign up' : 'Update your account', class: "btn btn-lg btn-primary btn-block btn-signin") %>

      <p class="signup-link"><%= link_to 'Log in', login_path %></p>
    </form>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>  <!-- to render errors template from views/shared folder !-->

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="card card-container">
    <p class='title'>Edit Your Profile</p>
    <form class="form-signin">
      <span id="reauth-email" class="reauth-email"></span>
      <%= f.label :name %>
      <%= f.text_field :name, id: "inputName", class: "form-control", autofocus: true %>
      <%= f.label :email %>
      <%= f.email_field :email, id: "inputEmail", class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, id: "inputPassword", class: "form-control" %>
      <%= f.label :confirm_password %>
      <%= f.password_field :password_confirmation, id: "inputPassword", class: "form-control" %>
      <%= f.submit(@user.new_record? ? 'Sign up' : 'Update your account', class: "btn btn-lg btn-primary btn-block btn-signin") %>
    </form>
  </div>
<% end %>

app/views/users/index.html.erb
<%= link_to 'Back to shop', product_path %>
<%= button_to 'Add to Cart', line_items_path(:product_id => product) %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= current_user.name %>'s profile</h1>

<p>
  <% if logged_in? && current_user.admin? %>
    You are Admin!
  <% end %>
</p>

<p>Your email is <%= current_user.email %></p>

<%= link_to "Edit profile", edit_user_path(current_user) %>