config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get '/signup' => 'users#new'
  resources :users, except: [:new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/users' => 'users#create'

  resources :line_items
  resources :carts
  resources :reviews
  resources :products
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
       <%= link_to "Urban Miami", products_path, class: "navbar-brand", id: "logo" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <%= form_tag(products_path, :method => "get", id: "search-form") do %>
        <li>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <%= text_field_tag :search, params[:search] %>
          <p class="submit"><%= submit_tag "Search", :name => nil %></p>
        <li>
      <% end %>

     <% if logged_in? %>

       <li>
         <%= link_to carts_path do %>
           <i class="fa fa-shopping-cart" aria-hidden="true"></i>
         <% end %>
       </li>
       <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
           <%= current_user.name %>
           <span class="caret"></span>
         </a>
         <ul class="dropdown-menu">
           <li class="dropdown-header header-nav-current-user">
             Signed in as <%= if current_user.admin? then "Admin" else current_user.name end %>
           </li>
           <li role="separator" class="divider"></li>
           <li><%= link_to "Shopping Cart" %></li>
           <li><%= link_to "View your profile", user_path(current_user) %></li>
           <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
           <li role="separator" class="divider"></li>
           <li><%= link_to 'Log out', logout_path, method: :delete %></li>
         </ul>
       </li>
     <% else %>
       <li><%= link_to 'Log in', login_path %></li>
       <li><%= link_to 'Sign up', signup_path %></li>
     <% end %>
   </ul>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urban Miami</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>